### ISSUE TITLE
Error on Decompress Script

### ISSUE THREAD

**Issue by druckgott** [Splines/deutsche-bahn-analysis#1]
Error with:
Traceback (most recent call last):
  File "f:\Python\deutsche-bahn-analysis-main\src\util\decompress.py", line 10, in <module>
    with open(os.path.join('./download', filename), 'rb') as f:
PermissionError: [Errno 13] Permission denied: './download\\8001354'

Can you help me? I´m on windows

**Comment by Splines** [comment]
It seems that there is a problem with the file permission. You might want to check that your current user has enough rights, e.g. see [here](https://stackoverflow.com/a/73311416/). Can you rename the file in the windows explorer and try to execute the decompression script again?

**Comment by druckgott** [comment]
I have taken a look. I update but I get the error again but if I add a output I think it´s not taking the file it take a folder.

![grafik](https://github.com/Splines/deutsche-bahn-analysis/assets/18383738/a781e93c-4993-4328-a5ab-2ae69fbbd5c1)

I added a Printout:
`print(os.path.join('./download', filename))`

```
(.venv) F:\Python\deutsche-bahn-analysis-main>f:/Python/deutsche-bahn-analysis-main/.venv/Scripts/python.exe f:/Python/deutsche-bahn-analysis-main/src/util/decompress.py
./download\8001354
Traceback (most recent call last):
  File "f:\Python\deutsche-bahn-analysis-main\src\util\decompress.py", line 11, in <module>
    with open(os.path.join('./download', filename), 'rb') as f:
PermissionError: [Errno 13] Permission denied: './download\\8001354'
```

**Comment by Splines** [comment]
Ah that's what you mean, I've updated the script accordingly, so that it only considers files not folders anymore. If you want to decompress a subfolder in downloads (semantically meaning the downloads for a specific station), you need to change the `base_path` now.

**Comment by druckgott** [comment]
Ok now I get no error.
How do I know that the main script works? I have someting in the uncompressed folger but only with 1k and if I run the decompress I get nothing in the decompressed folder. I have the feeling the Main script runs, but did not do what it sould do. Log says this:

```
1685717605.851424;2023-06-02 16:53:25;INFO;main.py;33;Start script called
1685717605.853423;2023-06-02 16:53:25;INFO;bahn.py;124;Station eva numbers are: { '8005626', '8005628'}
1685717605.853423;2023-06-02 16:53:25;INFO;bahn.py;126;Validate station folders
1685717640.857780;2023-06-02 16:54:00;INFO;bahn.py;135;Started bahn.py execution
1685717641.343157;2023-06-02 16:54:01;INFO;bahn.py;51;Calling endpoint: plan/8005626
1685717641.474792;2023-06-02 16:54:01;INFO;bahn.py;60;Calling endpoint: fchg/8005626
1685717641.606364;2023-06-02 16:54:01;INFO;bahn.py;51;Calling endpoint: plan/8005628
1685717641.722242;2023-06-02 16:54:01;INFO;bahn.py;60;Calling endpoint: fchg/8005628
```

**Comment by Splines** [comment]
1K as file size is perfectly fine and the log looks fine too, it called the respective endpoints. As I said, you will probably want to run the decompress script with `base_path = ./download/8005626` and then with `base_path = ./download/8005628` as these are the two stations you want to get data for.

The whole project is still a work a progress (though currently under no active development) and a lot of things are probably not conveniently set up for users tinkering with this repo for the first time. That you have to change the `base_path` manually is a good example for this. In the current state, think of this repo rather as a starting point for your own project than of a complete finalized product that "just runs". Happy coding ;)
